[package]
name = "glinfo"
version = "0.1.0"
edition = "2024"


[dependencies]
glutin = "*"
glutin-winit = "*"
winit = "*"

[build-dependencies]
gl_generator = "0.14"
cfg_aliases = "0.2.1"

[profile.release]
debug = 0
